name: Deploy Python Server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}               
        username: ubuntu                       
        port: 22                               
        key: ${{ secrets.PRIVATE_KEY }}         # SSH 프라이빗 키
        script: |
          # 파이썬 환경 확인 및 가상환경 설치
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip

          # 프로젝트 폴더가 있으면 pull, 없으면 clone
          if [ -d "/home/ubuntu/python-app" ]; then
            cd /home/ubuntu/python-app
            git pull origin main
          else
            git clone https://github.com/shim-pyoo/python.git /home/ubuntu/python-app
            cd /home/ubuntu/python-app
          fi

          # 가상환경 설정 및 패키지 설치
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # 서버 실행 (백그라운드에서 실행되도록)
          nohup python my_flask.py &
