name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your_dockerhub_username/flask-app:latest .
        docker push your_dockerhub_username/flask-app:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        port: 22
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Docker 설치
          sudo apt-get update
          sudo apt-get install -y docker.io
          
          # Docker Hub 로그인
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # 기존 컨테이너 중지 및 삭제
          docker stop flask-app || true
          docker rm flask-app || true
          
          # 최신 이미지를 받아서 실행
          docker pull your_dockerhub_username/flask-app:latest
          docker run -d -p 5001:5001 --name flask-app your_dockerhub_username/flask-app:latest
