name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    needs: build  # build가 완료되면 deploy 실행
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}  # EC2 IP 주소
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          docker stop flask-app || true
          docker rm flask-app || true
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker run -d -p 5001:5001 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
